services:
  db:
    image: mysql:8.0
    container_name: eskua-db
    env_file: ../.env
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - db_data:/var/lib/mysql
      - ../infra/db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      - eskua-net

  php:
    image: php:8.0-apache
    container_name: eskua-php
    env_file: ../.env
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    build:
      context: ../apps
      dockerfile: Dockerfile
    volumes:
      - ../infra/php/php.ini:/usr/local/etc/php/php.ini
      # Sacar del docker-compose en produccion y dejarlo todo en el Dockerfile (menos las imagenes)
      - ../apps/front_php/src:/var/www/html/
      - ../apps/backoffice_php/src:/var/www/html/backoffice/
      - ../apps/api:/var/www/html/api/
      - ../apps/backend:/var/www/backend/
      - ../apps/images:/var/www/html/images/
      - ../infra/apache/httpd.conf:/etc/apache2/sites-enabled/000-default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eskua-net

  auth_jwt:
    build:
      context: ../services/auth_jwt
      dockerfile: Dockerfile
    container_name: eskua-auth
    env_file: ../.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - eskua-net

networks:
  eskua-net:
    driver: bridge

volumes:
  db_data: